services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      LOWER_CASE_TABLE_NAMES: 1
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml
    environment:
      - SPRING_CONFIG_LOCATION=classpath:/,file:/app/application.yml
      - DB_URL=jdbc:mysql://mysql:3306/firstTask
      - DB_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
